apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting-app-container
        image: dipoelegbede/greeter-app:latest
        ports:
        - containerPort: 80
